import { useRef, useState } from 'react'
import { Button, EmptyState, Notice, PageHeader } from '../components/ui'
import { useAppData } from '../context/AppContext'
import { backupSummary, downloadBackup, parseBackup } from '../lib/backup'
import { formatDateTimeTW } from '../lib/utils'
import type { BackupData } from '../types'

export function BackupPage(): JSX.Element {
  const data = useAppData()
  const [backup, setBackup] = useState<BackupData | null>(null)
  const [raw, setRaw] = useState('')
  const [mode, setMode] = useState<'overwrite' | 'merge'>('merge')
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  const input = useRef<HTMLInputElement>(null)

  async function exportNow(): Promise<void> { try { const next = await data.exportBackup(); setBackup(next); downloadBackup(next); setMessage('完整 JSON 備份已下載。請將檔案保存到安全位置。'); setError('') } catch (caught) { setError(caught instanceof Error ? caught.message : '備份失敗。') } }
  async function readFile(file: File): Promise<void> { try { const text = await file.text(); const parsed = parseBackup(text); setRaw(text); setBackup(parsed); setMessage('備份檔已讀取，請確認摘要後選擇還原方式。'); setError('') } catch (caught) { setError(caught instanceof Error ? caught.message : '備份檔讀取失敗。'); setBackup(null) } }
  async function restore(): Promise<void> { if (!raw || !backup) return; const summary = backupSummary(backup); const warning = mode === 'overwrite' ? '覆蓋會清除目前本機資料，且建議先另存現有備份。' : '合併會依識別資料避免重複；同 ID 的資料保留目前版本。'; if (!window.confirm(`即將還原 ${summary.laws} 部法規、${summary.articles} 條法條、${summary.answers} 筆作答紀錄。${warning}\n\n確定繼續？`)) return; try { await data.restoreBackup(raw, mode); setMessage('備份還原完成，畫面已重新載入本機資料。'); setError('') } catch (caught) { setError(caught instanceof Error ? caught.message : '還原失敗，未完成資料變更。') } }
  return <div className="page-stack"><PageHeader eyebrow="BACKUP / LOCAL VAULT" title="備份與還原" description="完整備份包含法規、法條、項目、作答、錯題、熟練度、排程、任務、成就、混淆組與設定。" actions={<Button onClick={() => void exportNow()}>⤓ 匯出完整備份</Button>} />{message && <Notice tone="success">{message}</Notice>}{error && <Notice tone="warning">{error}</Notice>}<section className="backup-grid"><div className="card backup-export"><div className="backup-icon">⤓</div><p className="eyebrow">EXPORT / 匯出</p><h2>把本機資料帶走</h2><p>下載單一 JSON 檔，可保存到外接硬碟、雲端硬碟或其他安全位置；系統不會自動上傳。</p><div className="backup-counts"><span><strong>{data.laws.filter((law) => !law.deletedAt).length}</strong> 法規</span><span><strong>{data.articles.filter((article) => !article.deletedAt).length}</strong> 法條</span><span><strong>{data.answers.length}</strong> 作答</span><span><strong>{data.errors.length}</strong> 錯題</span></div><Button onClick={() => void exportNow()}>下載 JSON 備份</Button></div><div className="card backup-import"><div className="backup-icon">↥</div><p className="eyebrow">IMPORT / 還原</p><h2>從備份回到本機</h2><p>選擇 LexCore JSON 備份後，先查看摘要，再決定覆蓋或合併。</p><input ref={input} type="file" accept=".json,application/json" hidden onChange={(event) => { const file = event.target.files?.[0]; if (file) void readFile(file); event.target.value = '' }} /><Button variant="secondary" onClick={() => input.current?.click()}>選擇 JSON 備份</Button>{backup && <div className="backup-preview"><div><span>備份日期</span><strong>{formatDateTimeTW(backup.exportedAt)}</strong></div><div><span>法規 / 法條</span><strong>{backup.laws.length} / {backup.articles.length}</strong></div><div><span>作答 / 錯題</span><strong>{backup.answers.length} / {backup.errors.length}</strong></div><div className="restore-mode"><span>還原方式</span><label><input type="radio" checked={mode === 'merge'} onChange={() => setMode('merge')} /> 合併資料</label><label><input type="radio" checked={mode === 'overwrite'} onChange={() => setMode('overwrite')} /> 覆蓋現有資料</label></div><Button variant={mode === 'overwrite' ? 'danger' : 'gold'} onClick={() => void restore()}>確認還原</Button></div>}</div></section><section className="card backup-contract"><div><p className="eyebrow">DATA CONTRACT</p><h2>備份邊界</h2><p>備份檔可離線驗證 JSON 結構；還原不會呼叫網路服務。若檔案損壞、缺少必要陣列或不是 LexCore 格式，系統會拒絕還原。</p></div><div className="contract-list"><div><span>format</span><strong>lexcore-backup</strong></div><div><span>version</span><strong>0.1.0</strong></div><div><span>storage</span><strong>IndexedDB / 本機</strong></div></div></section>{!data.laws.length && !backup && <EmptyState icon="⤓" title="目前還沒有可備份資料" description="匯入法規與法條後，這裡會顯示完整資料摘要。" />}</div>
}
