import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button, EmptyState, ModeBadge, Notice, PageHeader } from '../components/ui'
import { useAppData } from '../context/AppContext'
import { formatDateTimeTW } from '../lib/utils'

export function ErrorsPage(): JSX.Element {
  const data = useAppData()
  const navigate = useNavigate()
  const [lawFilter, setLawFilter] = useState('all')
  const [kindFilter, setKindFilter] = useState('all')
  const [query, setQuery] = useState('')
  const errors = useMemo(() => [...data.errors].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).filter((error) => lawFilter === 'all' || error.lawId === lawFilter).filter((error) => kindFilter === 'all' || error.errors.some((item) => item.kind === kindFilter)).filter((error) => !query || error.originalText.includes(query) || error.userAnswer.includes(query)), [data.errors, kindFilter, lawFilter, query])
  const highWeightCount = data.errors.filter((error) => error.keywordErrors.length > 0).length
  return <div className="page-stack"><PageHeader eyebrow="ERRORS / REVIEW CENTER" title="錯題中心" description="每次錯誤都保留原文、你的答案、錯誤類型與高權重關鍵詞，方便回到訓練。" actions={<Button variant="secondary" onClick={() => navigate('/analytics')}>查看易錯分析 →</Button>} />{highWeightCount > 0 && <Notice tone="warning">目前有 {highWeightCount} 筆紀錄含高權重關鍵詞錯誤，建議先處理「得／應／不得」與項款順序。</Notice>}<section className="filter-bar card"><label>法規<select value={lawFilter} onChange={(event) => setLawFilter(event.target.value)}><option value="all">全部法規</option>{data.laws.filter((law) => !law.deletedAt).map((law) => <option value={law.id} key={law.id}>{law.name}</option>)}</select></label><label>錯誤類型<select value={kindFilter} onChange={(event) => setKindFilter(event.target.value)}><option value="all">全部類型</option><option value="missing">漏字</option><option value="extra">多字</option><option value="replacement">錯字</option><option value="keyword">關鍵詞</option><option value="structure">結構／順序</option></select></label><label className="search-box"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜尋原文或答案" /></label></section>{errors.length ? <div className="error-center-list">{errors.map((error) => { const article = data.articles.find((item) => item.id === error.articleId); const law = data.laws.find((item) => item.id === error.lawId); return <article className="error-center-card card" key={error.id}><div className="error-card-top"><div><p className="eyebrow">{law?.shortName ?? '未知法規'} · 第 {article?.articleNumber ?? '?'} 條</p><h2>{article?.title || '法條錯誤紀錄'}</h2></div><div className="error-card-meta"><ModeBadge mode={error.mode} /><span>{formatDateTimeTW(error.createdAt)}</span></div></div><div className="error-tallies"><span>正確率 <strong>{Math.round(error.accuracy)}%</strong></span><span>漏字 <strong>{error.missing.length}</strong></span><span>多字 <strong>{error.extra.length}</strong></span><span>錯字 <strong>{error.replacements.length}</strong></span><span>高權重 <strong className={error.keywordErrors.length ? 'negative' : ''}>{error.keywordErrors.length}</strong></span></div><div className="error-snippet"><div><span>你的答案</span><p>{error.userAnswer || '（未輸入）'}</p></div><div><span>需要修正</span><div className="error-chip-list">{error.errors.slice(0, 8).map((item, index) => <span className={item.isHighWeight ? 'high' : ''} key={`${item.kind}-${index}`}>{item.message}</span>)}</div></div></div><div className="card-actions"><Button onClick={() => article && navigate(`/training/${article.id}`)}>重新訓練</Button><details className="inline-details"><summary>查看原文</summary><p>{error.originalText}</p></details></div></article> })}</div> : <EmptyState icon="△" title="沒有符合條件的錯題" description={data.errors.length ? '可以清除篩選條件查看全部紀錄。' : '完成第一次訓練後，錯誤會在這裡累積。'} action={data.errors.length ? <Button variant="secondary" onClick={() => { setLawFilter('all'); setKindFilter('all'); setQuery('') }}>清除篩選</Button> : <Button onClick={() => navigate('/training')}>開始訓練</Button>} />}</div>
}
