import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button, EmptyState, ModeBadge, PageHeader } from '../components/ui'
import { useAppData } from '../context/AppContext'
import { formatDateTimeTW } from '../lib/utils'

export function RecordsPage(): JSX.Element {
  const data = useAppData()
  const navigate = useNavigate()
  const [mode, setMode] = useState('all')
  const [law, setLaw] = useState('all')
  const [score, setScore] = useState('all')
  const answers = useMemo(() => [...data.answers].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).filter((answer) => mode === 'all' || answer.mode === mode).filter((answer) => law === 'all' || answer.lawId === law).filter((answer) => score === 'all' || score === 'high' && answer.score >= 90 || score === 'low' && answer.score < 90), [data.answers, law, mode, score])
  const average = data.answers.length ? data.answers.reduce((sum, answer) => sum + answer.score, 0) / data.answers.length : 0
  const timeMinutes = data.sessions.reduce((sum, session) => sum + session.durationSeconds, 0) / 60
  const modes = new Map(data.answers.map((answer) => [answer.mode, 0]))
  data.answers.forEach((answer) => modes.set(answer.mode, (modes.get(answer.mode) ?? 0) + 1))
  return <div className="page-stack"><PageHeader eyebrow="RECORDS / STUDY LOG" title="學習紀錄" description="可依訓練模式、法規與分數篩選每一次已完成作答；紀錄會隨備份一起保留。" /><section className="record-summary"><div className="record-stat card"><span>總答題</span><strong>{data.answers.length}</strong><small>次</small></div><div className="record-stat card"><span>平均分數</span><strong>{Math.round(average)}</strong><small>分</small></div><div className="record-stat card"><span>學習時間</span><strong>{Math.round(timeMinutes)}</strong><small>分鐘</small></div><div className="record-stat card"><span>訓練模式</span><strong>{modes.size}</strong><small>種</small></div></section><section className="filter-bar card"><label>訓練模式<select value={mode} onChange={(event) => setMode(event.target.value)}><option value="all">全部模式</option><option value="comprehension">要件／效果／刑罰</option><option value="ordering">段落排序</option><option value="numbers">數字陷阱</option><option value="keywords">應／得陷阱</option><option value="cloze">舊版填空</option><option value="prompt">舊版提示默寫</option><option value="dictation">舊版完整默寫</option><option value="surprise">舊版突擊抽考</option></select></label><label>法規<select value={law} onChange={(event) => setLaw(event.target.value)}><option value="all">全部法規</option>{data.laws.filter((item) => !item.deletedAt).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>結果<select value={score} onChange={(event) => setScore(event.target.value)}><option value="all">全部分數</option><option value="high">90 分以上</option><option value="low">90 分以下</option></select></label></section>{answers.length ? <section className="records-table-card card"><div className="records-table"><div className="records-head"><span>日期</span><span>法條</span><span>模式</span><span>逐字</span><span>關鍵字</span><span>分數</span><span>提示</span><span /></div>{answers.map((answer) => { const article = data.articles.find((item) => item.id === answer.articleId); const lawItem = data.laws.find((item) => item.id === answer.lawId); return <div className="records-row" key={answer.id}><span>{formatDateTimeTW(answer.createdAt)}</span><span><strong>{lawItem?.shortName ?? '未知'} · 第 {article?.articleNumber ?? '?' } 條</strong><small>{article?.title || article?.text.slice(0, 36)}</small></span><ModeBadge mode={answer.mode} /><span>{Math.round(answer.accuracy)}%</span><span>{Math.round(answer.keywordAccuracy)}%</span><strong className={answer.score >= 90 ? 'positive' : 'negative'}>{Math.round(answer.score)}</strong><span>{answer.usedHints ? `${answer.usedHints} 級` : '無'}</span><Button variant="ghost" onClick={() => article && navigate(`/training/${article.id}`)}>重練</Button></div> })}</div></section> : <EmptyState icon="◷" title="沒有符合條件的紀錄" description={data.answers.length ? '調整篩選條件即可查看其他作答。' : '完成一次非閱讀模式的訓練後，這裡會保存學習紀錄。'} action={<Button onClick={() => navigate('/training')}>開始訓練</Button>} />}</div>
}
