import { Link, useNavigate } from 'react-router-dom'
import { Button, EmptyState, Notice, PageHeader, ProgressBar, StatusBadge } from '../components/ui'
import { useAppData } from '../context/AppContext'
import { taskTypeLabel } from '../lib/tasks'
import { formatRelativeReview, todayKey } from '../lib/utils'

export function TodayPage(): JSX.Element {
  const data = useAppData()
  const navigate = useNavigate()
  const tasks = data.tasks.filter((task) => task.date === todayKey()).sort((a, b) => Number(a.completed) - Number(b.completed))
  const completed = tasks.filter((task) => task.completed).length
  const totalMinutes = tasks.reduce((sum, task) => sum + task.estimatedMinutes, 0)
  const articles = data.articles.filter((article) => !article.deletedAt)
  const masteryMap = new Map(data.mastery.map((item) => [item.articleId, item]))

  return <div className="page-stack"><PageHeader eyebrow="TODAY / DAILY QUEUE" title="今日任務" description="任務依到期排程、錯題、必背標記與新法條自動產生，資料完全留在本機。" actions={<Button onClick={() => navigate(tasks.find((task) => !task.completed)?.articleId ? `/training/${tasks.find((task) => !task.completed)?.articleId}` : '/training')}>開始下一題 →</Button>} />{tasks.length > 0 && completed === tasks.length && <Notice tone="success"><strong>今日任務全部完成。</strong> 仍可前往突擊抽考或複習高風險法條。</Notice>}<section className="today-overview card"><div className="today-overview-score"><strong>{completed}</strong><span>/ {tasks.length} 已完成</span></div><div className="today-overview-details"><ProgressBar value={tasks.length ? (completed / tasks.length) * 100 : 0} label="今日完成率" tone="gold" /><div className="today-overview-meta"><span>預估 {totalMinutes} 分鐘</span><span>目標 {data.settings.dailyStudyMinutes} 分鐘</span><span>連續 {data.progress.streakDays} 天</span></div></div></section>{tasks.length ? <div className="task-list">{tasks.map((task) => { const article = articles.find((item) => item.id === task.articleId); const law = article ? data.laws.find((item) => item.id === article.lawId) : undefined; const mastery = masteryMap.get(task.articleId); return <article className={`daily-task card ${task.completed ? 'task-completed' : ''}`} key={task.id}><button className={`task-check ${task.completed ? 'checked' : ''}`} onClick={() => void data.toggleTask(task)} aria-label={task.completed ? '標記未完成' : '標記完成'}>{task.completed ? '✓' : ''}</button><div className="daily-task-main"><div className="task-type-line"><span className={`task-type task-${task.type}`}>{taskTypeLabel(task.type)}</span><span>{task.estimatedMinutes} 分鐘</span></div>{article ? <><h3>{law?.shortName ?? law?.name} · 第 {article.articleNumber} 條</h3><p>{article.title || article.text.slice(0, 76)}{article.title ? ` · ${article.text.slice(0, 70)}…` : '…'}</p></> : <h3>法條已不存在</h3>}</div><div className="daily-task-side">{mastery && <StatusBadge status={mastery.status} />}{article && <span className="task-review-time">{data.reviews.find((review) => review.articleId === article.id) ? formatRelativeReview(data.reviews.find((review) => review.articleId === article.id)?.nextReviewAt) : '尚未安排'}</span>}<div className="row-actions"><Button variant="secondary" onClick={() => article && navigate(`/training/${article.id}`)} disabled={!article}>訓練</Button><Link className="button button-ghost" to={article ? `/articles?law=${article.lawId}` : '/articles'}>查看</Link></div></div></article> })}</div> : <EmptyState icon="▣" title={articles.length ? '今天沒有自動任務' : '尚無法條可產生任務'} description={articles.length ? '可以到設定調高每日新法條數，或直接開始自由訓練。' : '匯入已校對的法條後，系統會在本機自動產生今日任務。'} action={<Button onClick={() => navigate(articles.length ? '/training' : '/articles')}>{articles.length ? '自由開始訓練' : '前往匯入法條'}</Button>} />}</div>
}
